# Grammar {#grammar}

::: blockquote

Grammar  makes  language  expressive.  A  language  consisting  of  words and no grammar (statement = word) expresses only as many ideas as there are words. By specifying how words are combined in statements, a grammar expands a language’s scope.

-- Wilkinson, 2005, The Grammar of Graphics, 2nd edition

:::

Chapter \@ref(basics) described a number of basic terms and concepts in experimental designs. In this chapter, I dissect these basic terms in order to build the "grammar of experimental designs". 
The so-called grammar of experimental designs is a term that is heavily influenced by @Wilkinson2005-oz, who use the term "grammar of graphics" to describe an object-oriented system to create unlimited number of plots from following a relatively small number of rules. The grammar of graphics is adopted across many systems (Julia, Python, R, Tableau and so on) with its most popular interpretation as the `ggplot2` R-package [@ggplot2]. An overview of `ggplot2` is given in Section \@ref(ggplot). The grammar of experimental designs leverage aspects of the grammar of graphics for the visualisation of the experimental designs as discussed more extensively in \@ref(deggust). 

Henceforth, "grammar" refers to the grammar of experimental designs.

## Fundamental terminology

Section \@ref(terminology) describe the basic terminology used in the field of experimental design. We can, however, describe some terms more fundamentally by considering every categorised entity (physical or otherwise) involved in the experiment to be a **factor** in the design. The two primary roles of a factor are **treatments** and **units**; under this categorisation blocks, experimental unit and observational unit are all just units -- the specific role of the unit is determined by the relationship of the factors. For example, if a treatment factor is allocated to a plot factor, then the plot is an experimental unit. 

In the grammar, an intermediate construct of the experimental design is stored as an object that contain two types of directed graphs, $G_F = (V(G_F), E(G_F))$ and $G_L = (V(G_L), E(G_L))$, where $V(G_F)$ and $V(G_L)$ are sets of vertices and $E(G_F)$ and $E(G_L)$ are sets of edges. We refer $G_F$ and $G_L$ as factor graph and level graph, respectively. In the **factor graph**, every factor is represented as a single vertex. Every factor has a finite number of levels and each of these levels is represented as a single vertex in the **level graph**.

```{r edibble-graph, message = FALSE, echo = FALSE}
des <- start_design("Split plot design") %>%
  set_units(mainplot = 4,
             subplot = nested_in(mainplot, 4)) %>%
  set_trts(irrigation = c("rainfed", "irrigated"),
           fertilizer = c("brand-A", "brand-B")) %>%
  allot_trts(irrigation ~ mainplot,
             fertilizer ~ subplot) %>%
  assign_trts("random", seed = 592)
plot(des, view = "static", seed = 3, height = "200px",
     title = c("Factor graph for a split plot design" = "font-weight:bold;text-align:center;"))
plot(des, which = "levels", view = "static", height = "400px", seed = 1,
     title = c("Level graph for a split plot design" = "font-weight:bold;text-align:center;"))
```

