project:
  type: book
  output-dir: _book


book:
  title: "The Grammar of Experimental Designs"
  author: "Emi Tanaka"
  site-url: https:://emitanaka.org/edibble-book
  repo-url: https://github.com/emitanaka/edibble-book
  repo-branch: master
  repo-actions: [edit, issue]
  google-analytics: G-ZBRNTDT9WG
  image: figures/logos/edibble-website-logo-blue.png
  favicon: figures/logos/favicon.ico
  sharing: [twitter, facebook]
  sidebar:
    logo: figures/logos/edibble-website-logo-blue.png
  chapters:
    - index.qmd
    - preface.qmd
    
    - part: basics.qmd
      chapters:
        - basics-terminology.qmd
        - basics-principles.qmd
        - basics-choices.qmd
        - basics-diagnosis.qmd
        - basics-analysis.qmd
        - basics-summary.qmd
    - part: grammar.qmd
      chapters:
        - grammar-ed.qmd
        - grammar-graphics.qmd
        - grammar-edvis.qmd
    - part: practice.qmd
      chapters:
        - practice-consulting.qmd
        - practice-management.qmd
        - practice-context.qmd
        - practice-guides.qmd
    - part: toolbox.qmd
      chapters:
        - toolbox-edibble.qmd
    - part: cookbook.qmd
      chapters:
        - cookbook-crd.qmd
        - cookbook-rcbd.qmd
        - cookbook-lsd.qmd
        - cookbook-factorial.qmd
        - cookbook-bibd.qmd
        - cookbook-split.qmd
        - cookbook-strip.qmd
  appendices:
    - references.qmd

#comments:
#  hypothesis: true
       
bibliography: book.bib

format:
  html:
    theme: 
     - style.scss
    header-includes: |
      <link rel="stylesheet" href="/assets/fontawesome-free-6.1.1-web/css/font-awesome.min.css">
      <script defer src="/assets/fontawesome-free-6.1.1-web/js/all.min.js"></script>
      <script defer data-domain="emitanaka.org/edibble-book" src="https://plausible.io/js/plausible.js"></script>
  #pdf:
  #  documentclass: scrreprt



