on:
  push:
    branches: master
  pull_request:
    branches: master
  # to be able to trigger a manual build
  workflow_dispatch:

name: quarto-book

jobs:
  quarto-book:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Query dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install libmagick++-dev
          
      - name: Query R dependencies
        run: |
          install.packages('remotes')
          remotes::install_github("emitanaka/simulate")
          remotes::install_github("emitanaka/edibble")
          remotes::install_github("emitanaka/deggust")
          install.packages("openxlsx")
          install.packages("bslib")
          install.packages("downlit")
          install.packages("xml2")
          install.packages("visNetwork")
          install.packages("MASS")
        shell: Rscript {0}

      - uses: r-lib/actions/setup-renv@v2

      - name: Render book to all format
        # Add any command line argument needed
        run: |
          quarto render
          
      - name: Deploy 🚀
        # only deploy when push to main
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: _book
