on:
  push:
    branches: master
  pull_request:
    branches: master
  # to be able to trigger a manual build
  workflow_dispatch:

name: quarto-book

jobs:
  quarto-book:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Query dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install libmagick++-dev
          
      - name: Query R dependencies
        run: |
          install.packages('remotes')
          remotes::install_github("emitanaka/simulate")
          remotes::install_github("emitanaka/edibble")
          remotes::install_github("emitanaka/deggust")
          install.packages("openxlsx")
          install.packages("bslib")
          install.packages("downlit")
          install.packages("xml2")
          install.packages("visNetwork")
          install.packages("agridat")
        shell: Rscript {0}

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
